import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {resetFolioDbForTests} from '../folio-db/init.js';
import {state,saveState,savePrivate,readPrivate,guard} from './store.js';
import {begin,complete,configure} from './google.js';
import {zurichTime,matches,draftFromSource,validate} from './planning.js';
let dir:string;
beforeEach(()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-09-20T12:00:00Z'));dir=mkdtempSync(join(tmpdir(),'folio-calendar-'));vi.stubEnv('FOLIO_DB_PATH',join(dir,'folio.db'));vi.stubEnv('FOLIO_VAULT_OVERRIDE',join(dir,'vault'));});
afterEach(()=>{resetFolioDbForTests();vi.useRealTimers();vi.unstubAllEnvs();vi.unstubAllGlobals();rmSync(dir,{recursive:true,force:true});});
const d={sourceId:'s',sourceRef:'mail:test:1',summary:'Besichtigung',location:'Beispielstr. 9, 4000 Basel',start:'2026-09-08T12:30:00.000Z',end:'2026-09-08T12:50:00.000Z'};
it('uses Zurich summer and winter offsets',()=>{expect(zurichTime('2026-09-08T14:30')).toBe(d.start);expect(zurichTime('2026-12-08T14:30')).toBe('2026-12-08T13:30:00.000Z');});
it('rejects nonexistent DST time and invalid dates',()=>{expect(()=>zurichTime('2026-03-29T02:30')).toThrow();expect(()=>zurichTime('2026-02-30T12:00')).toThrow();});
it('matches an existing timed event with exact location despite title difference',()=>{expect(matches(d,[{id:'e',summary:'Wohnung anschauen',location:d.location,start:{dateTime:d.start},end:{dateTime:d.end}}])).toHaveLength(1);});
it('never treats changed time, cancelled or all-day events as confirmed duplicates',()=>{expect(matches(d,[{id:'e',summary:d.summary,start:{dateTime:d.start},end:{dateTime:'2026-09-08T13:00:00Z'}},{id:'c',status:'cancelled',summary:d.summary,start:{dateTime:d.start},end:{dateTime:d.end}},{id:'a',summary:d.summary,start:{date:'2026-09-08'},end:{date:'2026-09-09'}}])).toEqual([]);});
it('matches all-day ranges using Google Calendar exclusive end dates',()=>{const allDay={...d,start:'2026-09-21',end:'2026-09-24',allDay:true};expect(matches(allDay,[{id:'course',summary:d.summary,start:{date:'2026-09-21'},end:{date:'2026-09-24'}}])).toHaveLength(1);expect(matches(allDay,[{id:'short',summary:d.summary,start:{date:'2026-09-21'},end:{date:'2026-09-23'}}])).toEqual([]);});
it('extracts viewing time without inventing participants',()=>{const x=draftFromSource({fact_id:'f',source_ref:'mail:test:1',valid_from:'2026-09-08',value_text:'Besichtigung Beispielstr. 9, 4000 Basel (4 Zimmer) am 2026-09-08 von 14:30 bis 14:50 Uhr'});expect(x?.location).toBe(d.location);expect(x?.start).toBe(d.start);expect(x).not.toHaveProperty('attendees');});
it('proposes a visible 30 minute duration when the mail only names a start time',()=>{const x=draftFromSource({fact_id:'voss',source_ref:'mail:gmail:7149',valid_from:'2026-09-24',value_text:'RAV-Beratung mit Insa Voss am 2026-09-24 um 10:00 Uhr. Ende nicht angegeben; Terminvorschlag aus der Mail vom 03.07.2026.'});expect(x).toMatchObject({summary:'RAV-Beratung mit Insa Voss',start:'2026-09-24T08:00:00.000Z',end:'2026-09-24T08:30:00.000Z'});expect(x?.assumption).toContain('30 Minuten');});
it('leaves missing times unresolved',()=>{expect(draftFromSource({fact_id:'f',source_ref:'x',valid_from:'2026-09-08',value_text:'Besichtigung nächste Woche'})).toBeNull();});
it('requires exact configured callback URI',()=>{expect(()=>configure(JSON.stringify({web:{client_id:'test.apps.googleusercontent.com',client_secret:'test',redirect_uris:['http://localhost/other']}}),'http://localhost/calendar/callback')).toThrow();});
it('binds OAuth to browser cookie and consumes state before token exchange',async()=>{savePrivate('client',{client_id:'test.apps.googleusercontent.com',client_secret:'test',redirect_uri:'http://localhost/calendar/callback'});const b=begin(false);const network=vi.fn();vi.stubGlobal('fetch',network);await expect(complete('code',b.nonce,'wrong')).rejects.toThrow();expect(network).not.toHaveBeenCalled();network.mockResolvedValue(new Response('{}',{status:400}));await expect(complete('code',b.nonce,b.nonce)).rejects.toThrow();expect(readPrivate('oauth')).toBeNull();await expect(complete('code',b.nonce,b.nonce)).rejects.toThrow();expect(network).toHaveBeenCalledTimes(1);});
it('starts with read-only scopes and uses PKCE',()=>{savePrivate('client',{client_id:'test.apps.googleusercontent.com',client_secret:'test',redirect_uri:'http://localhost/calendar/callback'});const u=new URL(begin(false).url);expect(u.searchParams.get('scope')).toContain('calendar.events.readonly');expect(u.searchParams.get('scope')).not.toContain('calendar.events.owned');expect(u.searchParams.get('code_challenge_method')).toBe('S256');});
it('isolates selected calendar cache and denies demo access',()=>{saveState({calendarId:'one',events:[]});expect(state().calendarId).toBe('one');vi.stubEnv('FOLIO_VAULT_OVERRIDE',join(dir,'demo-vault'));expect(()=>guard()).toThrow();});
it('rejects invalid event bounds',()=>{expect(()=>validate({...d,end:d.start})).toThrow();});
it('keeps past timed and all-day events blocked at a fixed clock',()=>{expect(()=>validate(d)).toThrow('Vergangene Termine');expect(()=>validate({...d,start:'2026-09-18',end:'2026-09-19',allDay:true})).toThrow('Vergangene Termine');});
it('rejects malformed or duplicate attendees before preparing a calendar write',()=>{const draft=futureDraft();expect(()=>validate({...draft,attendees:[{role:'Frau',email:'invalid'}]})).toThrow();expect(()=>validate({...draft,attendees:[{role:'Frau',email:'same@example.test'},{role:'Tochter',email:'SAME@example.test'}]})).toThrow();});
it('validates exact all-day date ranges without requiring fabricated times',()=>{expect(validate({...d,start:'2026-09-21',end:'2026-09-24',allDay:true})).toMatchObject({allDay:true});expect(()=>validate({...d,start:'21.09.2026',end:'2026-09-24',allDay:true})).toThrow();});
import {db} from './store.js';
import {prepare,pending,createApproved,recordedCalendarSourceIds,calendarEventsWithDomains} from './planning.js';
function seed(){db().prepare(`INSERT INTO memory_facts(fact_id,domain,data_class,sensitivity,subject,predicate,value_text,status,source_kind,source_ref,recorded_at) VALUES ('s','immo','event','private','Owner','scheduled_for','Besichtigung','candidate','mail','mail:test:1',?)`).run(new Date().toISOString());saveState({calendarId:'cal',writeEnabled:true,events:[]});savePrivate('tokens',{access_token:'test',refresh_token:'test',expires_at:Date.now()+3600000});}
function futureDraft(){const start=new Date(Date.now()+86400000*3);return {...d,start:start.toISOString(),end:new Date(start.getTime()+1200000).toISOString()};}
it('preview never sends a calendar request',()=>{seed();const network=vi.fn();vi.stubGlobal('fetch',network);const id=prepare(futureDraft());expect(pending(id)?.status).toBe('pending');expect(network).not.toHaveBeenCalled();});
it('rejects changed calendar or missing write permission before any Google request',async()=>{seed();const id=prepare(futureDraft());saveState({calendarId:'other',writeEnabled:true,events:[]});const network=vi.fn();vi.stubGlobal('fetch',network);await expect(createApproved(id,'owner:1')).rejects.toThrow();expect(network).not.toHaveBeenCalled();});
it('refreshes before creation and does not create an existing event',async()=>{seed();const draft=futureDraft(),id=prepare(draft);const network=vi.fn().mockResolvedValue(new Response(JSON.stringify({items:[{id:'existing',summary:draft.summary,location:draft.location,start:{dateTime:draft.start},end:{dateTime:draft.end}}]})));vi.stubGlobal('fetch',network);expect(await createApproved(id,'owner:1')).toContain('bereits vorhanden');expect(network).toHaveBeenCalledTimes(1);expect(pending(id)?.status).toBe('existing');});
it('creates only after approval, omits guests, and keeps one stable event ID per draft',async()=>{seed();const draft=futureDraft(),id=prepare(draft),eventId=pending(id)!.event_id;const requests:Array<{url:string;init:RequestInit}>=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit)=>{requests.push({url,init});return new Response(JSON.stringify(init.method==='POST'?{id:'created'}:{items:[]}));}));await createApproved(id,'owner:1');const write=requests.find(r=>r.init.method==='POST')!;expect(write.url).toContain('sendUpdates=none');const body=JSON.parse(write.init.body as string);expect(body).not.toHaveProperty('attendees');expect(body.id).toBe(eventId);expect(body.id).toMatch(/^[a-f0-9]{64}$/);expect(body.extendedProperties.private.folioSource).toBe('s');expect(pending(id)?.status).toBe('created');await expect(createApproved(id,'owner:1')).rejects.toThrow();expect(requests.filter(r=>r.init.method==='POST')).toHaveLength(1);});
it('sends only the displayed invitees after approval',async()=>{seed();const draft={...futureDraft(),attendees:[{role:'Frau',email:'wife@example.test'},{role:'Tochter',email:'daughter@example.test'}],invitationRuleId:'family-school-v1'},id=prepare(draft);const requests:Array<{url:string;init:RequestInit}>=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit)=>{requests.push({url,init});return new Response(JSON.stringify(init.method==='POST'?{id:'created'}:{items:[]}));}));expect(await createApproved(id,'owner:1')).toContain('2 Einladungen');const write=requests.find(r=>r.init.method==='POST')!;expect(write.url).toContain('sendUpdates=all');expect(JSON.parse(write.init.body as string).attendees).toEqual([{email:'wife@example.test'},{email:'daughter@example.test'}]);});
it('uses a fresh event ID when the owner creates a new draft after deleting an earlier event',()=>{seed();const first=prepare(futureDraft()),second=prepare(futureDraft());expect(pending(first)!.event_id).toMatch(/^[a-f0-9]{64}$/);expect(pending(second)!.event_id).not.toBe(pending(first)!.event_id);});
it('uses a successful creation receipt only while its event is still live in the selected calendar',()=>{seed();const id=prepare(futureDraft()),eventId=pending(id)!.event_id;db().prepare("UPDATE calendar_drafts SET status='created' WHERE id=?").run(id);const live={id:eventId,summary:'Legacy-shaped appointment',start:{dateTime:d.start},end:{dateTime:d.end}};saveState({calendarId:'cal',events:[live]});expect(recordedCalendarSourceIds([live])).toEqual(new Set(['s']));expect(recordedCalendarSourceIds([])).toEqual(new Set());saveState({calendarId:'other',events:[live]});expect(recordedCalendarSourceIds([live])).toEqual(new Set());});
it('decorates linked events with the mail-domain palette and leaves unrelated events neutral',()=>{seed();db().prepare("UPDATE memory_facts SET domain='career' WHERE fact_id='s'").run();const id=prepare(futureDraft()),eventId=pending(id)!.event_id;db().prepare("UPDATE calendar_drafts SET status='created' WHERE id=?").run(id);const events=[{id:eventId,summary:'Course',start:{dateTime:d.start},end:{dateTime:d.end}},{id:'manual',summary:'Manual',start:{dateTime:d.start},end:{dateTime:d.end}}];expect(calendarEventsWithDomains(events).map(event=>event.domain)).toEqual(['job','unsorted']);});
it('creates an approved all-day range without inventing date-times',async()=>{seed();const draft={...d,start:'2026-09-21',end:'2026-09-24',allDay:true},id=prepare(draft);const requests:Array<{url:string;init:RequestInit}>=[];vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit)=>{requests.push({url,init});return new Response(JSON.stringify(init.method==='POST'?{id:'created'}:{items:[]}));}));await createApproved(id,'owner:1');const body=JSON.parse(requests.find(r=>r.init.method==='POST')!.init.body as string);expect(body.start).toEqual({date:'2026-09-21'});expect(body.end).toEqual({date:'2026-09-24'});expect(JSON.stringify(body)).not.toContain('dateTime');});

import {calendarConflicts,calendarMatches,sameStart} from './planning.js';
import {sync,writeGranted} from './google.js';
it('shows a same-start end-time discrepancy without confirming the source',async()=>{
 seed();
 db().prepare("UPDATE memory_facts SET value_text=?,valid_from=? WHERE fact_id='s'").run('Besichtigung Teststr. 9, 4051 Basel (4 Zimmer) am 2026-09-08 von 14:30 bis 14:50 Uhr','2026-09-08');
 saveState({calendarId:'cal',syncedAt:new Date().toISOString(),events:[{id:'e',summary:'Besichtigungstermin Teststrasse 9',location:'Teststrasse 9, 4051 Basel, Schweiz',start:{dateTime:d.start},end:{dateTime:'2026-09-08T13:00:00Z'}}]});
 expect(calendarConflicts().s).toContain('14:30–15:00');
 expect(calendarConflicts().s).toContain('Mail: 14:30–14:50');
 expect(await calendarMatches()).toEqual({});
 expect(db().prepare('SELECT * FROM calendar_source_links').all()).toEqual([]);
});
it('does not flag cancelled, all-day or different-start events as same-start conflicts',()=>{
 expect(sameStart(d,[{id:'c',status:'cancelled',start:{dateTime:d.start},end:{dateTime:d.end}},{id:'a',start:{date:'2026-09-08'},end:{date:'2026-09-09'}},{id:'other',start:{dateTime:'2026-09-08T15:00:00Z'},end:{dateTime:'2026-09-08T16:00:00Z'}}])).toEqual([]);
});
it('persists only hashed guest response states and drops raw guest data and descriptions',async()=>{
 seed();vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({items:[{id:'e',summary:'Meeting',start:{dateTime:d.start},end:{dateTime:d.end},description:'private body',attendees:[{email:'guest@example.invalid',responseStatus:'accepted'}]}]}))));
 await sync();expect(state().events[0]).toMatchObject({id:'e',summary:'Meeting',attendeeResponses:[{responseStatus:'accepted'}]});expect(state().events[0]).not.toHaveProperty('description');expect(state().events[0]).not.toHaveProperty('attendees');expect(JSON.stringify(state().events[0])).not.toContain('guest@example.invalid');
});

it('derives granted write access from OAuth scopes independently of the selected calendar',()=>{savePrivate('tokens',{refresh_token:'test',scope:'https://www.googleapis.com/auth/calendar.events.owned'});saveState({calendarId:'read-only-subscription',writeEnabled:false,events:[]});expect(writeGranted()).toBe(true);savePrivate('tokens',{refresh_token:'test',scope:'https://www.googleapis.com/auth/calendar.events.readonly'});expect(writeGranted()).toBe(false);});

it.each([
 {same:true, scenario:'reconnect retains a calendar verified in the new calendar list'},
 {same:false, scenario:'reconnect with different account drops the previous calendar'}
])('$scenario',async({same})=>{
 savePrivate('client',{client_id:'test.apps.googleusercontent.com',client_secret:'test',redirect_uri:'http://localhost/calendar/callback'});
 saveState({calendarId:'original',calendarName:'Old',syncedAt:'2026-09-01',events:[{id:'private',start:{date:'2026-09-21'},end:{date:'2026-09-22'}}]});
 const login=begin(false);
 const network=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:'access',refresh_token:'refresh',expires_in:3600,scope:'https://www.googleapis.com/auth/calendar.events.readonly'})))
 .mockResolvedValueOnce(new Response(JSON.stringify({items:[{id:same?'original':'other',summary:'Calendar',accessRole:'owner'}]})));
 vi.stubGlobal('fetch',network);await complete('code',login.nonce,login.nonce);
 expect(state().calendarId).toBe(same?'original':undefined);expect(state().events).toEqual([]);expect(state().syncedAt).toBeUndefined();expect(state().writeEnabled).toBe(false);
 expect(state().calendarName).toBe(same?'Calendar':undefined);
 expect(network).toHaveBeenCalledTimes(2);
});
