import {createHash,randomUUID} from 'node:crypto';
import {db,state,audit,type CalendarEvent} from './store.js';
import {google,sync} from './google.js';
import {calendarDomain} from '$lib/calendar/domain.js';
export interface EventDraft {sourceId:string;sourceRef:string;summary:string;location:string;start:string;end:string;allDay?:boolean;assumption?:string;attendees?:Array<{role:string;email:string}>;invitationRuleId?:string;}
export interface CalendarSource {fact_id:string;domain:string;data_class:string;subject:string;predicate:string;value_text:string;valid_from:string|null;source_ref:string;status:string;}
export function zurichTime(local:string){if(!/^\d{4}-\d\d-\d\dT\d\d:\d\d$/.test(local))throw new Error('Datum und Uhrzeit fehlen.');const guess=Date.parse(local+'Z');if(!Number.isFinite(guess))throw new Error('Ungültiges Datum.');const fmt=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Zurich',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const candidates:string[]=[];for(const offset of [60,120]){const d=new Date(guess-offset*60000);if(fmt.format(d).replace(' ','T')===local)candidates.push(d.toISOString());}if(candidates.length===1)return candidates[0];if(candidates.length>1)throw new Error('Diese Uhrzeit ist wegen der Zeitumstellung doppeldeutig.');throw new Error('Diese Uhrzeit existiert wegen der Zeitumstellung nicht.');}
function normalize(s:string){return s.toLowerCase().replace(/strasse|straße|str\./g,'str').replace(/[^a-z0-9äöü]/g,'');}
export function matches(d:EventDraft,events:CalendarEvent[]){return events.filter(e=>{if(e.status==='cancelled')return false;const sameTime=d.allDay?e.start.date===d.start&&e.end.date===d.end:!!e.start.dateTime&&!!e.end.dateTime&&Math.abs(Date.parse(e.start.dateTime)-Date.parse(d.start))<60000&&Math.abs(Date.parse(e.end.dateTime)-Date.parse(d.end))<60000;return sameTime&&((d.location.length>8&&normalize(e.location??'')===normalize(d.location))||normalize(e.summary??'')===normalize(d.summary));});}
export function sameStart(d:EventDraft,events:CalendarEvent[]){return events.filter(e=>e.status!=='cancelled'&&(d.allDay?e.start.date===d.start:!!e.start.dateTime&&Math.abs(Date.parse(e.start.dateTime)-Date.parse(d.start))<60000));}
export function calendarConflicts(){const s=state(),result:Record<string,string>={};if(!s.calendarId)return result;const time=(v:string)=>new Intl.DateTimeFormat('de-CH',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Zurich'}).format(new Date(v));for(const source of sources()){const d=draftFromSource(source);if(!d||matches(d,s.events).length===1)continue;const found=sameStart(d,s.events);if(found.length){const descriptions=found.map(e=>`${e.summary??'Ohne Titel'} (${time(e.start.dateTime!)}${e.end.dateTime?'–'+time(e.end.dateTime):''})`).join('; ');result[source.fact_id]=`Im Kalender beginnt zur selben Zeit: ${descriptions}. Mail: ${time(d.start)}–${time(d.end)}. Details abgleichen; keine automatische Neuanlage.`;}}return result;}
export function validate(d:EventDraft){const datesValid=d.allDay?/^\d{4}-\d{2}-\d{2}$/.test(d.start)&&/^\d{4}-\d{2}-\d{2}$/.test(d.end):Number.isFinite(Date.parse(d.start))&&Number.isFinite(Date.parse(d.end));if(!d.summary.trim()||d.summary.length>500||d.location.length>500||!datesValid||Date.parse(d.end)<=Date.parse(d.start))throw new Error('Titel, Beginn und Ende prüfen.');if(Date.parse(d.start)<Date.now()-86400000)throw new Error('Vergangene Termine werden nicht neu angelegt.');const emails=(d.attendees??[]).map(invitee=>invitee.email.trim().toLocaleLowerCase('en-US'));if(emails.length>10||new Set(emails).size!==emails.length||emails.some(email=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)))throw new Error('Einladungskontakte prüfen.');return d;}
export function sources(){return db().prepare("SELECT fact_id,domain,data_class,subject,predicate,value_text,valid_from,source_ref,status FROM memory_facts WHERE predicate='scheduled_for' AND status IN ('candidate','confirmed') ORDER BY recorded_at DESC").all() as CalendarSource[];}
/**
 * Sources whose successful local creation receipt still points at a live event.
 * This bridges older drafts whose stored date shape differs from today's proposal
 * projection, without hiding an event that the owner later deleted in Google.
 */
export function recordedCalendarSourceIds(events:CalendarEvent[]){
	const calendarId=state().calendarId;if(!calendarId)return new Set<string>();
	const liveIds=new Set(events.map(event=>event.id));
	const rows=db().prepare("SELECT value,event_id FROM calendar_drafts WHERE status='created'").all() as {value:string;event_id:string|null}[];
	const result=new Set<string>();
	for(const row of rows){
		if(!row.event_id||!liveIds.has(row.event_id))continue;
		try{const value=JSON.parse(row.value) as {calendarId?:string;draft?:{sourceId?:string}};if(value.calendarId===calendarId&&value.draft?.sourceId)result.add(value.draft.sourceId);}catch{/* Ignore malformed historical receipts. */}
	}
	return result;
}
/** Decorate only locally-linked events; unrelated Google events remain neutral. */
export function calendarEventsWithDomains(events:CalendarEvent[]){
	const calendarId=state().calendarId;if(!calendarId||!events.length)return events.map(event=>({...event,domain:calendarDomain(event.domain)}));
	const liveIds=new Set(events.map(event=>event.id)),sourceByEvent=new Map<string,string>();
	const links=db().prepare('SELECT source_id,event_id FROM calendar_source_links WHERE calendar_id=?').all(calendarId) as {source_id:string;event_id:string}[];
	for(const link of links)if(liveIds.has(link.event_id))sourceByEvent.set(link.event_id,link.source_id);
	const receipts=db().prepare("SELECT value,event_id FROM calendar_drafts WHERE status='created'").all() as {value:string;event_id:string|null}[];
	for(const receipt of receipts){
		if(!receipt.event_id||!liveIds.has(receipt.event_id))continue;
		try{const value=JSON.parse(receipt.value) as {calendarId?:string;draft?:{sourceId?:string}};if(value.calendarId===calendarId&&value.draft?.sourceId)sourceByEvent.set(receipt.event_id,value.draft.sourceId);}catch{/* Ignore malformed historical receipts. */}
	}
	const sourceIds=[...new Set(sourceByEvent.values())],domainBySource=new Map<string,string>();
	if(sourceIds.length){
		const rows=db().prepare(`SELECT fact_id,domain FROM memory_facts WHERE fact_id IN (${sourceIds.map(()=>'?').join(',')})`).all(...sourceIds) as {fact_id:string;domain:string}[];
		for(const row of rows)domainBySource.set(row.fact_id,row.domain);
	}
	return events.map(event=>({...event,domain:calendarDomain(domainBySource.get(sourceByEvent.get(event.id)??'')??event.domain)}));
}
export function prepare(d:EventDraft){validate(d);const s=state();if(!s.calendarId)throw new Error('Kein Kalender ausgewählt.');const source=sources().find(i=>i.fact_id===d.sourceId);if(!source||source.source_ref!==d.sourceRef)throw new Error('Terminquelle ist nicht mehr verfügbar.');const id=randomUUID(),eventId=createHash('sha256').update(s.calendarId+'\n'+d.sourceId+'\n'+id).digest('hex');db().prepare('INSERT INTO calendar_drafts VALUES (?,?,?,?)').run(id,JSON.stringify({draft:d,calendarId:s.calendarId,createdAt:Date.now()}),'pending',eventId);return id;}
export function pending(id:string){const row=db().prepare('SELECT * FROM calendar_drafts WHERE id=?').get(id) as {id:string;value:string;status:string;event_id:string}|undefined;return row?{...row,...JSON.parse(row.value) as {draft:EventDraft;calendarId:string;createdAt:number}}:null;}
const running=new Set<string>();
export async function createApproved(id:string,actor:string){const p=pending(id);if(!p||p.status!=='pending'||p.createdAt<Date.now()-3600000)throw new Error('Freigabe ist nicht mehr aktuell. Bitte Vorschau erneuern.');const s=state();if(s.calendarId!==p.calendarId||!s.writeEnabled)throw new Error('Schreibzugriff auf den ausgewählten Kalender fehlt.');if(running.has(p.event_id))throw new Error('Dieser Termin wird bereits verarbeitet.');running.add(p.event_id);try{const fresh=await sync();const duplicates=matches(p.draft,fresh.events);if(duplicates.length){db().prepare("UPDATE calendar_drafts SET status='existing' WHERE id=?").run(id);audit('existing',{sourceId:p.draft.sourceId,eventId:duplicates[0].id});return 'Der Termin ist bereits vorhanden. Keine Neuanlage.';}if(!p.draft.allDay&&fresh.events.some(e=>e.start.dateTime&&Math.abs(Date.parse(e.start.dateTime)-Date.parse(p.draft.start))<60000))throw new Error('Zur selben Zeit besteht bereits ein Termin. Bitte mögliche Dublette oder Abweichung im Kalender klären.');validate(p.draft);audit('create_approved',{draftId:id,actor,eventId:p.event_id,invitationRuleId:p.draft.invitationRuleId??null,invitationCount:p.draft.attendees?.length??0});const path='/calendars/'+encodeURIComponent(p.calendarId)+'/events';const existing=await google(path+'?'+new URLSearchParams({privateExtendedProperty:'folioSource='+p.draft.sourceId}));if(existing.items?.length)throw new Error('Für diese Quelle wurde bereits ein Termin angelegt. Bitte bestehenden Termin prüfen.');const start=p.draft.allDay?{date:p.draft.start}:{dateTime:p.draft.start,timeZone:'Europe/Zurich'},end=p.draft.allDay?{date:p.draft.end}:{dateTime:p.draft.end,timeZone:'Europe/Zurich'},attendees=p.draft.attendees??[];await google(path+'?sendUpdates='+(attendees.length?'all':'none'),{method:'POST',body:JSON.stringify({id:p.event_id,summary:p.draft.summary,location:p.draft.location,start,end,description:'Quelle in Folio: '+p.draft.sourceRef,extendedProperties:{private:{folioSource:p.draft.sourceId}},reminders:{useDefault:true},...(attendees.length?{attendees:attendees.map(invitee=>({email:invitee.email}))}:{})})});db().prepare("UPDATE calendar_drafts SET status='created' WHERE id=?").run(id);audit('created',{draftId:id,eventId:p.event_id,invitationCount:attendees.length});await sync();return attendees.length?`Termin angelegt und ${attendees.length} Einladungen versandt.`:'Termin angelegt. Keine Einladungen versandt.';}finally{running.delete(p.event_id);}}
export function draftFromSource(s:{fact_id:string;source_ref:string;value_text:string;valid_from:string|null}):EventDraft|null {const date=s.value_text.match(/\d{4}-\d\d-\d\d/)?.[0]??s.valid_from?.slice(0,10),times=s.value_text.match(/\d{1,2}:\d\d/g);if(!date||!times?.length||times.length>2)return null;try{const summary=s.value_text.replace(/\s+am\s+\d{4}-\d\d-\d\d.*$/,'').replace(/\s+on\s+\d{4}-\d\d-\d\d.*$/i,'').trim();const location=/^Besichtigung /i.test(summary)?summary.replace(/^Besichtigung /i,'').replace(/\s*\([^)]*\)/g,'').trim():'';const start=zurichTime(date+'T'+times[0].padStart(5,'0'));const explicitEnd=times.length===2;return {sourceId:s.fact_id,sourceRef:s.source_ref,summary,location,start,end:explicitEnd?zurichTime(date+'T'+times[1].padStart(5,'0')):new Date(Date.parse(start)+30*60_000).toISOString(),...(explicitEnd?{}:{assumption:'Die Mail nennt keine Endzeit. Folio schlägt 30 Minuten vor; bitte vor der Freigabe prüfen.'})};}catch{return null;}}
export async function calendarMatches(){const {connected}=await import('./google.js');if(!connected())return {} as Record<string,string>;let s=state();if(!s.calendarId)return {};if(!s.syncedAt||Date.now()-Date.parse(s.syncedAt)>300000)s=await sync();const result:Record<string,string>={};for(const source of sources()){const d=draftFromSource(source);if(d){const found=matches(d,s.events);if(found.length===1){result[source.fact_id]=found[0].id;db().prepare('INSERT INTO calendar_source_links VALUES (?,?,?,?) ON CONFLICT(source_id,calendar_id) DO UPDATE SET event_id=excluded.event_id,verified_at=excluded.verified_at').run(source.fact_id,s.calendarId,found[0].id,s.syncedAt);}else db().prepare('DELETE FROM calendar_source_links WHERE source_id=? AND calendar_id=?').run(source.fact_id,s.calendarId);}}return result;}
