<script lang="ts">
 import {enhance} from '$app/forms';
 import type {PageData,ActionData} from './$types';
 let {data,form}:{data:PageData;form:ActionData}=$props();
</script>
<svelte:head><title>Einstellungen · Folio</title><meta name="referrer" content="no-referrer"/></svelte:head>
<main><header><span>FOLIO</span><h1>Einstellungen</h1></header>
{#if form?.message}<p role="status">{form.message}</p>{/if}{#if data.warning}<p role="alert">{data.warning}</p>{/if}
<section id="calendar"><div class="heading"><h2>Kalender</h2><a href="/calendar">Übersicht →</a></div>
{#if !data.configured}<details><summary>Google-Zugang einrichten</summary><code>{data.redirectUri}</code><form method="POST" action="?/configure" use:enhance><label>Client-JSON<textarea name="client" rows="4" required autocomplete="off" spellcheck="false"></textarea></label><button>Speichern</button></form></details>
{:else if !data.connected}<a class="button" href="/calendar/connect" data-sveltekit-reload data-sveltekit-preload-data="off">Mit Google verbinden</a>
{:else}<small>{data.state.writeEnabled?'Termine nach Freigabe anlegen':'Lesender Zugriff'}</small><form method="POST" action="?/select" use:enhance><label>Kalender<select name="calendar" required>{#each data.calendars as c}<option value={c.id} selected={c.id===data.state.calendarId}>{c.summary}</option>{/each}</select></label><button>Übernehmen</button></form><div class="actions">{#if data.warning}<a class="button" href={data.state.writeEnabled?'/calendar/connect?write=yes':'/calendar/connect'} data-sveltekit-reload data-sveltekit-preload-data="off">Erneut verbinden</a>{/if}<form method="POST" action="?/sync" use:enhance><button class="secondary">Aktualisieren</button></form>{#if !data.state.writeEnabled}<a class="button" href="/calendar/connect?write=yes" data-sveltekit-reload data-sveltekit-preload-data="off">Schreibzugriff aktivieren</a>{/if}</div><details><summary>Verbindung verwalten</summary><small>{data.state.calendarName}</small><form method="POST" action="?/disconnect" use:enhance><button class="secondary">Verbindung trennen</button></form></details>{/if}</section>
<section><h2>Mail & Übergaben</h2><a class="row" href="/mail-intake">Automatischer Maileingang <span>→</span></a><a class="row" href="/relay">Projektkontext und Übergaben <span>→</span></a></section><section><h2>Werkzeuge</h2><a class="row" href="/pipeline">Pipeline und Modelle →</a><a class="row" href="/inbox">Import-Prüfstapel →</a><a class="row" href="/memory/backfill">Datei-Wissensprüfung →</a><a class="row" href="/memory/graph">Wissensgraph →</a></section></main>
<style>
 main{max-width:840px;margin:auto;padding:28px 24px 80px;background:var(--color-background);color:var(--color-foreground);min-height:100%;font-family:system-ui,sans-serif}header{margin:16px 0 28px}header span{font:11px ui-monospace,monospace;color:var(--color-foreground);letter-spacing:.12em}h1{font-size:30px;font-weight:500;margin:12px 0}h2{font-size:19px;font-weight:550;margin:0 0 14px}section{padding:22px;margin:20px 0;border:1px solid var(--color-border);border-radius:10px;background:var(--color-card)}.heading,.actions,.row{display:flex;justify-content:space-between;align-items:center;gap:16px}.actions{justify-content:flex-start;flex-wrap:wrap;margin:16px 0}a{color:var(--color-foreground)}label{display:grid;gap:8px;margin:16px 0}textarea,select{width:100%;min-width:0;box-sizing:border-box;padding:12px;border:1px solid var(--color-border);border-radius:6px;background:var(--color-background);color:inherit;font:inherit}button,.button{display:inline-block;padding:12px 16px;min-height:44px;border:0;border-radius:6px;background:var(--color-foreground);color:var(--color-background);font:14px system-ui;cursor:pointer;text-decoration:none}.secondary{background:var(--color-muted);color:var(--color-foreground)}small{display:block;color:var(--color-muted-foreground);line-height:1.6;overflow-wrap:anywhere}summary{cursor:pointer;padding:12px 0}code{overflow-wrap:anywhere}.row{padding:14px 0;border-bottom:1px solid var(--color-border);text-decoration:none}details form{margin-top:12px}@media(max-width:640px){main{padding:20px 16px 70px}section{padding:16px}.heading{align-items:flex-start}}
</style>
