import {describe,it,expect} from 'vitest';
import {detectContractEvent,projectContractEvents,parseContractDay,type ContractMailInput,type ContractMailProfile,type ContractMailEvent} from './contract-mail-events.js';
import type {ContractInventory} from '$lib/ledger-contracts.js';
const profile:ContractMailProfile={id:'editor',reviewOnly:false,accounts:['mail'],senders:['billing@editor.test'],domains:['editor.test'],products:['Editor Pro'],exclude:['Editor API']};
const input:ContractMailInput={id:4,date:'2026-09-24T10:00:00Z',sender:'billing@editor.test',subject:'Your Editor Pro subscription was canceled',body:'Your Editor Pro subscription has been successfully canceled. Your access will expire on October 23, 2026.',account:'mail',complete:true,eligible:true,hash:'a'.repeat(64)};
const event=(overrides:Partial<ContractMailEvent>={}):ContractMailEvent=>({...detectContractEvent(input,[profile])!,id:'event',...overrides});
const base=():ContractInventory=>({schema:'folio/contracts-inventory/v1',as_of:'2026-09-24',batch_sha256:'b'.repeat(64),coverage:{mail_rows:1,mail_with_text:1,bank_entries:1,bank_through:'2026-08-31',accounts:['mail'],limitations:[]},items:[{id:'editor',label:'Editor Pro',group:'KI & Software',status:'observed',priority:'high',cost:'20 CHF',summary:'Known',next_step:'Check',unknowns:[],timing:null,evidence:[{kind:'bank',id:'txn_'+'a'.repeat(24),sha256:'b'.repeat(64),date:'2026-08-23',label:'Payment',note:'Bank'}]}]});
describe('contract mail decisions',()=>{
 it('recognizes a complete cancellation and explicit end date',()=>{expect(event()).toMatchObject({kind:'cancelled',contractId:'editor',until:'2026-10-23'});expect(detectContractEvent({...input,account:'mail-history'},[profile])?.kind).toBe('cancelled');});
 it('recognizes an explicit German confirmation but holds conditional FAQ text',()=>{expect(detectContractEvent({...input,subject:'Kündigung Ihres Editor Pro Vertrags',body:'Wir bestätigen die Kündigung Ihres Editor Pro Abos. Es endet am 23.10.2026.'},[profile])).toMatchObject({kind:'cancelled',until:'2026-10-23'});expect(detectContractEvent({...input,subject:'Cancellation request for Editor Pro',body:'If your subscription was canceled, you can reactivate it.'},[profile])?.kind).toBe('review');});
 it('does not turn cancellation links, offers or invoice footers into cancellations',()=>{expect(detectContractEvent({...input,subject:'Come back for 50% off'},[profile])).toBeNull();expect(detectContractEvent({...input,subject:'Your Editor Pro invoice',body:'Editor Pro. Total CHF 20.00. If your subscription was canceled you may still receive this invoice.'},[profile])?.kind).toBe('invoice');});
 it('distinguishes plus tiers from a base tier',()=>{const p={...profile,products:['Editor Pro+']};expect(detectContractEvent(input,[p])?.kind).toBe('review');expect(detectContractEvent({...input,subject:input.subject.replace('Pro','Pro+'),body:input.body.replaceAll('Pro','Pro+')},[p])?.kind).toBe('cancelled');});
 it('requires review for aggregate vendor accounts even when the product matches',()=>{expect(detectContractEvent(input,[{...profile,reviewOnly:true}])?.kind).toBe('review');});
 it('keeps incomplete, forwarded, wrong account and spoofed senders for review',()=>{for(const patch of [{complete:false},{subject:'Fwd: '+input.subject},{account:'another'},{sender:'billing@editor.test.evil.test'},{sender:'Editor Pro <billing@unknown.test>'}])expect(detectContractEvent({...input,...patch},[profile])?.kind).toBe('review');});
 it('requires product identity when one provider has multiple plans',()=>{expect(detectContractEvent({...input,subject:'Your Editor API subscription was canceled',body:'Your Editor API subscription was canceled.'},[profile])?.kind).toBe('review');expect(detectContractEvent(input,[profile,{...profile,id:'editor-two'}])?.reason).toContain('Mehrere');});
 it('does not consider a request received or failed cancellation a confirmation',()=>{expect(detectContractEvent({...input,subject:'Cancellation request',body:'We received your request for Editor Pro.'},[profile])?.kind).toBe('review');expect(detectContractEvent({...input,body:'Your Editor Pro subscription was not canceled.'},[profile])?.kind).toBe('review');});
 it('extracts only explicit unambiguous totals and does not guess dollar currency',()=>{const invoice={...input,subject:'Editor Pro invoice',body:'Editor Pro. Subtotal CHF 10.00 Total CHF 10.81'};expect(detectContractEvent(invoice,[profile])?.amount).toBe('10.81 CHF');expect(detectContractEvent({...invoice,body:'Editor Pro Total $10.81'},[profile])?.amount).toBeNull();expect(detectContractEvent({...invoice,body:'Editor Pro Total CHF 10.81 Amount paid EUR 12.00'},[profile])?.amount).toBeNull();});
 it('rejects excluded folders and detects invalid dates',()=>{expect(detectContractEvent({...input,eligible:false},[profile])).toBeNull();expect(detectContractEvent({...input,date:''},[profile])?.kind).toBe('review');for(const s of ['February 31, 2026','31.02.2026','not a date'])expect(parseContractDay(s)).toBeNull();expect(parseContractDay('13. November 2026')).toBe('2026-11-13');});
});
describe('chronological contract projection',()=>{
 it('changes only the matched contract and preserves the reviewed base',()=>{const b=base(),out=projectContractEvents(b,[event()]);expect(b.items[0].status).toBe('observed');expect(out.inventory.items[0]).toMatchObject({status:'cancelled',priority:'low',timing:{date:'2026-10-23'}});});
 it('does not overwrite newer evidence with a late historical cancellation',()=>{expect(projectContractEvents(base(),[event({date:'2026-07-01T12:00:00Z'})]).changed).toEqual([]);});
 it('never reactivates a cancelled contract because a later invoice arrives',()=>{const out=projectContractEvents(base(),[event({id:'invoice',mailId:5,date:'2026-09-25T10:00:00Z',kind:'invoice',amount:'40 CHF'}),event()]);expect(out.inventory.items[0].status).toBe('cancelled');expect(out.notices[0].reason).toContain('Restlaufzeit');expect(out.inventory.items[0].cost).toBe('20 CHF');});
 it('corroborates an owner-confirmed cancellation with an older mail without changing its timing',()=>{const b=base();b.items[0].status='cancelled';const out=projectContractEvents(b,[event({date:'2026-07-01T12:00:00Z'})]);expect(out.inventory.items[0].status).toBe('cancelled');expect(out.inventory.items[0].timing).toBeNull();expect(out.inventory.items[0].evidence).toHaveLength(2);});
 it('keeps a refund separate from the contract state',()=>{const out=projectContractEvents(base(),[event({kind:'refund'})]);expect(out.inventory.items[0].status).toBe('observed');expect(out.notices).toHaveLength(1);});
 it('marks amounts as supplier evidence, never as a confirmed bank payment',()=>{const out=projectContractEvents(base(),[event({kind:'invoice',amount:'25 CHF'})]);expect(out.inventory.items[0].cost).toBe('25 CHF laut Anbieterbeleg');expect(out.inventory.items[0].next_step).toContain('keine Bankzahlung');});
});
