import {describe,it,expect} from 'vitest';
import {buildExpenseHierarchy,expenseBranch} from './household-hierarchy.js';
import type {HouseholdEntry} from '$lib/ledger-household.js';
const entry=(id:string,title:string,purpose='',amount=-25,category:HouseholdEntry['category']='subscriptions'):HouseholdEntry=>({id,title,purpose,amount,display_amount:amount*1.1,category,date:'2026-08-26',currency:'CHF',account:'Bank',aggregate:false});
describe('hierarchical expenses',()=>{
 it('groups recurring merchants despite varying references and dates',()=>{const a=entry('a','Vodafone West GmbH KDNR 123 RGN 456'),b=entry('b','VODAFONE WEST GMBH KDNR 123 RGN 789');expect(expenseBranch(a).partner.id).toBe(expenseBranch(b).partner.id);const tree=buildExpenseHierarchy([a,b]);expect(tree[0].children[0].label).toBe('Telefon & Internet');expect(tree[0].children[0].partners).toMatchObject([{label:'Vodafone',count:2}]);expect(tree[0].children[0].partners[0].amount).toBeCloseTo(55);});
 it('uses the underlying merchant from payment-service descriptions',()=>{const p=expenseBranch(entry('a','PayPal Europe','Lastschrift für Netflix.com'));expect(p.partner.label).toBe('Netflix');expect(p.label).toBe('Streaming');const salt=expenseBranch(entry('b','LASTSCHRIFT','UBS SWITZERLAND AG\nSALT MOBILE SA'));expect(salt.partner.label).toBe('Salt');});
 it('preserves every debit exactly once and reconciles every level in display currency',()=>{const entries=[entry('a','Vodafone'),entry('b','STRATO', '',-13),entry('c','GALAXUS','',-299,'equipment'),entry('d','Unknown','',-15,'unknown'),entry('credit','Vodafone','',30)];const tree=buildExpenseHierarchy(entries);expect(tree.reduce((n,c)=>n+c.count,0)).toBe(4);expect(tree.reduce((n,c)=>n+c.amount,0)).toBeCloseTo((25+13+299+15)*1.1);for(const c of tree){expect(c.children.reduce((n,s)=>n+s.amount,0)).toBeCloseTo(c.amount);expect(c.children.reduce((n,s)=>n+s.count,0)).toBe(c.count);for(const s of c.children){expect(s.partners.reduce((n,p)=>n+p.amount,0)).toBeCloseTo(s.amount);expect(s.partners.reduce((n,p)=>n+p.count,0)).toBe(s.count);}}});
 it('does not merge unrelated unnamed TWINT or PayPal payments',()=>{for(const label of ['TWINT KAUF/DIENSTLEISTUNG','PayPal Europe']){const a=expenseBranch(entry('a',label,'merchant unknown')),b=expenseBranch(entry('b',label,'another merchant'));expect(a.partner.id).not.toBe(b.partner.id);expect(a.partner.tentative).toBe(true);}});
 it('does not change the existing parent category or invent a subcategory',()=>{const e=entry('a','Amazon','',-20,'unknown');const path=expenseBranch(e);expect(path.subcategory).toBe('other');expect(buildExpenseHierarchy([e])[0].id).toBe('unknown');expect(buildExpenseHierarchy([e])[0].children[0].label).toBe('Noch einzuordnen');});
 it('separates bank fees by account and keeps an empty selection empty',()=>{const a=entry('a','Entgeltabrechnung'),b={...entry('b','Entgeltabrechnung'),account:'Other bank'};expect(expenseBranch(a).partner.id).not.toBe(expenseBranch(b).partner.id);expect(buildExpenseHierarchy([])).toEqual([]);});
});
