<script lang="ts">
 import {onMount,tick,untrack} from 'svelte';
 import {chatStore} from '$lib/stores/chat.svelte.js';
 import {page} from '$app/state';
 import {householdSelection} from '$lib/ledger-household.js';
 import {Landmark,House,Wallet,CalendarRange,ArrowUpRight,X,ArrowRight} from 'lucide-svelte';
 import HouseholdTimeline from '$lib/components/ledger/HouseholdTimeline.svelte';
 import HouseholdExpenses from '$lib/components/ledger/HouseholdExpenses.svelte';
 import HouseholdDrilldown from '$lib/components/ledger/HouseholdDrilldown.svelte';
 import WealthDetails from '$lib/components/ledger/WealthDetails.svelte';
 import {expenseCategories,householdTimeline,monthLabel,selectedMonths,viewMonths,type CategoryId,type ExpenseKind,type HouseholdDirection,type HouseholdView} from '$lib/ledger-household.js';
 import '$lib/components/ledger/household.css';
 import type {PageData} from './$types.js';
 let {data}:{data:PageData}=$props();
 onMount(()=>{const previous={...chatStore.context};chatStore.setContext({view:'ledger-books',selectedItem:'Haushaltsbuch'});return ()=>chatStore.setContext(previous);});
 let start=$state(Math.max(0,untrack(()=>data.household?.months.length??0)-6)),end=$state(untrack(()=>data.household?.months.length??0)),horizon=$state(3);
 let selected=$state(''),category=$state<CategoryId|''>(''),group=$state<ExpenseKind|''>(''),detailMonth=$state(''),direction=$state<'debit'|'credit'|'all'>('debit'),detailPanel=$state<HTMLElement>();
 let view=$state<HouseholdView>('household');
 const views=[{id:'household',label:'Haushalt'},{id:'accounts',label:'Kontobewegungen'},{id:'transfers',label:'Überträge'}] as const;
 function changeView(next:HouseholdView){view=next;selected='';treeMonth='';}
 let treeDirection=$state<HouseholdDirection>('debit'),treeMonth=$state(''),treeCategory=$state(''),treePanel=$state<HTMLElement>();
 $effect(()=>{
  const params=new URLSearchParams(page.url.search);
  untrack(()=>{const selection=householdSelection(params,data.household?.months??[]);if(selection){start=selection.start;end=selection.end;view=selection.view;treeDirection=selection.direction;treeCategory=selection.category??'';treeMonth='';selected='';}});
 });
 const h=$derived(data.household),months=$derived(h?selectedMonths(h,start,end,view):[]),timeline=$derived(h?householdTimeline(h,start,end,horizon,view):[]);
 const allMonths=$derived(h?viewMonths(h,view):[]);
 const estimatedFees=$derived(months.reduce((n,m)=>n+(m.fees?.estimated??0),0));
 const treeMonths=$derived(treeMonth?months.filter(m=>m.month===treeMonth):months);
 const treeTotal=$derived(treeMonths.reduce((n,m)=>n+(treeDirection==='debit'?m.outgoing:m.incoming),0));
 async function showTree(month='',kind:HouseholdDirection=treeDirection){treeMonth=month;treeDirection=kind;await tick();if(treePanel&&treePanel.getBoundingClientRect().top>window.innerHeight*.65)treePanel.scrollIntoView({block:'start',behavior:'smooth'});}
 const period=$derived(months.length===1?monthLabel(months[0].month,true):months.length?monthLabel(months[0].month,true)+' – '+monthLabel(months.at(-1)!.month,true):'');
 const totals=$derived({incoming:months.reduce((s,m)=>s+m.incoming,0),outgoing:months.reduce((s,m)=>s+m.outgoing,0),net:months.reduce((s,m)=>s+m.net,0)});
 const sources=$derived(h?.income_sources.map((s,i)=>({...s,amount:months.reduce((n,m)=>n+(m.income[s.id]??0),0),color:['blue','purple','orange','gray'][i%4],days:s.end_date?Math.round((Date.parse(s.end_date)-Date.parse(h.as_of))/86400000):null}))??[]);
 const money=(n:number)=>new Intl.NumberFormat('de-CH',{maximumFractionDigits:0}).format(Math.round(n/100)*100)+' '+(h?.currency==='CHF'?'CHF':'€');
 const expenseTitle=$derived(category?expenseCategories.find(c=>c.id===category)?.label:group==='fixed'?'Fixkosten':group==='variable'?'Variable Ausgaben':group==='unknown'?'Zuordnung offen':group==='transfer'?'Überträge':direction==='credit'?'Zugänge':direction==='all'?'Kontobewegungen':'Ausgaben');
 const maxFlow=$derived(Math.max(1,...allMonths.map(m=>m.incoming+m.outgoing)));
 const coverageGaps=$derived(h?months.filter(m=>m.coverage.length<Math.max(...h.months.map(m=>m.coverage.length))).length:0);
 function slide(which:'start'|'end',value:number){if(!h)return 0;if(which==='start')start=Math.max(0,Math.min(value,end-1));else end=Math.min(h.months.length,Math.max(value,start+1));detailMonth='';treeMonth='';return which==='start'?start:end;}
 async function open(key:string){selected=key;await tick();detailPanel?.scrollIntoView({block:'nearest',behavior:'smooth'});}
 function expenses(c:CategoryId|''='',g:ExpenseKind|''='',m='',d:'debit'|'credit'|'all'='debit'){category=c;group=g;detailMonth=m;direction=d;void open('entries');}
</script>
<svelte:head><title>Folio · Haushaltsbuch</title><meta name="robots" content="noindex, nofollow"/></svelte:head>
<main id="folio-household">
 <div class="hh-content">
  <header class="hh-heading"><h1>Dein Haushaltsbuch</h1><a href="/ledger/contracts" style="margin-left:auto;font-size:13px;color:var(--hh-blue);text-decoration:none">Abos & Fixkosten ↗</a><button onclick={()=>open('scope')}>Datenstand & Umfang ↗</button></header>
  {#if !h}<section class="hh-detail"><h2>Haushaltsübersicht nicht verfügbar</h2><p>{data.householdError}</p>{#if data.overview}<WealthDetails data={{overview:data.overview,stale:data.stale,error:data.error}}/>{/if}</section>
  {:else}
   {#if h.stale}<p class="hh-small-note" role="status">Neuere Kontoauszüge vorhanden. Der Vermögensstand muss aktualisiert werden; eine Projektion bleibt bis dahin ausgeblendet.</p>{/if}
   <nav class="hh-view-switch hh-proj" aria-label="Haushaltsansicht">{#each views as v}<button aria-pressed={view===v.id} onclick={()=>changeView(v.id)}>{v.label}</button>{/each}</nav>
   <section class="hh-overview" aria-label="Jüngster erfasster Vermögensstand">
    <button class="hh-metric" style="--metric-color:var(--hh-blue)" onclick={()=>open('wealth')}><Landmark/><strong>{h.assets_low===h.assets_high?money(h.assets_low):money(h.assets_low).replace(/ (CHF|€)$/,'')+'–'+money(h.assets_high)}</strong><span>Vermögenswerte · geschätzt</span></button>
    {#if h.property}<button class="hh-metric" style="--metric-color:var(--hh-purple)" onclick={()=>open('house')}><House/><strong>{money(h.property.price)}</strong><span>{h.property.paid?'Hauskauf · Preisbasis':'Im Hauskauf gebunden'}</span></button>{/if}
    <button class="hh-metric" style="--metric-color:var(--hh-orange)" onclick={()=>open('liquidity')}><Wallet/><strong>≈ {money(h.after_purchase??h.liquid)}</strong><span>{h.after_purchase!==null?'Liquide nach Kaufpreis':'Erfasste liquide Mittel'}</span>{#if h.after_purchase!==null}<small>vor Restkosten</small>{/if}</button>
   </section>
   <div class="hh-columns"><div class="hh-left">
    <section class="hh-panel hh-bars-panel"><div class="hh-panel-top"><div><h2>{view==='household'?'Einnahmen & Ausgaben':view==='transfers'?'Überträge zwischen Konten':'Kontobewegungen'}</h2><p>{period} · {view==='household'?'ohne bestätigte Eigenüberträge':view==='transfers'?'Bankseiten · keine Haushaltseinnahmen':'brutto · inklusive Überträge'}</p></div><button class="hh-icon-button" onclick={()=>expenses('','','','all')} aria-label="Kontobewegungen öffnen"><ArrowUpRight/></button></div><HouseholdTimeline {view} rows={timeline} mode="bars" selectedMonth={treeMonth} selectedDirection={treeDirection} onmonth={(m,d)=>showTree(m,d??treeDirection)} onprojection={()=>open('projection')}/><div class="hh-legend"><span><i class="hh-dot" style="--swatch:var(--hh-blue)"></i>{view==='household'?'Einnahmen':'Zugänge'} <button class="hh-entry-link" onclick={()=>showTree('','credit')}>{money(totals.incoming)}</button></span><span><i class="hh-dot" style="--swatch:var(--hh-orange)"></i>{view==='household'?'Ausgaben':'Abgänge'} <button class="hh-entry-link" onclick={()=>showTree('','debit')}>{money(totals.outgoing)}</button></span></div></section>

    <section class="hh-panel hh-flow-panel"><div class="hh-panel-top"><div><h2>{view==='household'?'Cashflow':'Bewegungssaldo'}</h2><p>{view==='household'?'Haushaltsüberschuss':'Summe der erfassten Bankseiten'} · {h.currency}</p></div>{#if h.forecast&&view==='household'}<div class="hh-proj" aria-label="Projektionshorizont"><button aria-pressed={horizon===3} disabled={end!==h.months.length} onclick={()=>horizon=3}>+3 M.</button><button aria-pressed={horizon===6} disabled={end!==h.months.length} onclick={()=>horizon=6}>+6 M.</button></div>{/if}</div><HouseholdTimeline {view} rows={timeline} mode="cashflow" selectedMonth={treeMonth} selectedDirection={treeDirection} onmonth={(m,d)=>showTree(m,d??treeDirection)} onprojection={()=>open('projection')} band={h.forecast?.band??1500}/><div class="hh-legend"><span><i class="hh-dot" style="--swatch:var(--hh-blue)"></i>{view==='household'?'Bereinigt':'Gebucht'}</span>{#if timeline.some(m=>!m.actual)}<span><i class="hh-line-key"></i><button onclick={()=>open('projection')}>Vorläufiger Ausblick</button></span>{/if}{#if coverageGaps}<button onclick={()=>open('scope')}>{coverageGaps} Monate mit lückenhafter Abdeckung</button>{/if}</div></section>
   {#if h.property}<div class="hh-home"><div class="hh-home-main"><House/><div><strong>{h.property.label} · {money(h.property.price)} {h.property.paid?'Kaufpreisbasis':'gebunden'}</strong><p>{h.property.paid?'Zahlung laut hinterlegtem Stand':'Noch unbezahlt · Erwerb in Abwicklung'} · noch keine Miete angesetzt</p></div></div><button onclick={()=>open('house')}>Abrechnung <ArrowUpRight/></button></div>{/if}
   <section class="hh-period" aria-label="Zeitraum für alle Diagramme">
    <div class="hh-period-head"><label for="hh-period-start"><CalendarRange/>Zeitraum</label><output aria-live="polite">{period}</output></div>
    <div class="hh-range" style={`--start:${start/h.months.length*100}%;--end:${end/h.months.length*100}%`}><div class="hh-minibars" style={`grid-template-columns:repeat(${h.months.length},1fr);gap:${h.months.length>24?2:5}px`} aria-hidden="true">{#each allMonths as m,i}<span class:selected={i>=start&&i<end} style={`height:${(m.incoming+m.outgoing)/maxFlow*100}%`}></span>{/each}</div><div class="hh-selected-track"></div><input id="hh-period-start" type="range" min="0" max={h.months.length} value={start} step="1" data-range="start" aria-label="Erster dargestellter Monat" aria-valuetext={monthLabel(h.months[start].month,true)} oninput={(e)=>e.currentTarget.value=String(slide('start',Number(e.currentTarget.value)))}/><input type="range" min="0" max={h.months.length} value={end} step="1" data-range="end" aria-label="Letzter dargestellter Monat" aria-valuetext={monthLabel(h.months[end-1].month,true)} oninput={(e)=>e.currentTarget.value=String(slide('end',Number(e.currentTarget.value)))}/><span class="hh-coarse-label">Von <span>{monthLabel(h.months[start].month,true)}</span></span><span class="hh-coarse-label">Bis <span>{monthLabel(h.months[end-1].month,true)}</span></span></div>
    <div class="hh-range-foot"><span>{monthLabel(h.months[0].month,true)}</span><span>{end-start} {end-start===1?'Monat':'Monate'}</span><span>{monthLabel(h.months.at(-1)!.month,true)}</span></div>
   </section>
   {#if selected}<section id="household-detail" class="hh-detail" bind:this={detailPanel}>
    <header><h2>{selected==='entries'?`${expenseTitle} · ${detailMonth?monthLabel(detailMonth,true):period}`:selected==='wealth'?'Konten, Depots & Vermögenswerte':selected==='house'?'Hauskauf · Abrechnung':selected==='liquidity'?'Liquidität nach Kaufpreis':selected==='projection'?'Cashflow · Annahmen':'Datenstand & Umfang'}</h2><button class="hh-icon-button" aria-label="Details schliessen" onclick={()=>selected=''}><X/></button></header>
    {#if selected==='entries'}
     {#key `${months[0].month}:${months.at(-1)!.month}:${detailMonth}:${category}:${group}:${direction}:${h.batch_sha256}`}<HouseholdDrilldown {view} from={detailMonth||months[0].month} to={detailMonth||months.at(-1)!.month} batch={h.batch_sha256} currency={h.currency} {category} {group} {direction}/>{/key}
    {:else if selected==='wealth'&&data.overview}<WealthDetails data={{overview:data.overview,stale:data.stale,error:data.error}}/>
    {:else if selected==='house'&&h.property}
     <div class="hh-detail-row"><span>Kaufpreis gesamt</span><strong>{money(h.property.price)}</strong></div><div class="hh-detail-row"><span>Immobilie / Inventar</span><strong>{money(h.property.property)} / {money(h.property.inventory)}</strong></div><div class="hh-detail-row"><span>Zahlung</span><strong>{h.property.paid?'Laut hinterlegtem Stand bezahlt':'Noch nicht bezahlt'}</strong></div><div class="hh-detail-row"><span>Restliche Erwerbskosten</span><strong>Abgleich offen</strong></div><p>{h.property.source} · Stand {h.property.confirmed_at}. Der Kaufpreis wird bei unbezahltem Erwerb nur als gebundene Liquidität dargestellt und nicht nochmals auf das vorhandene Vermögen addiert. Der neue Notarbrief und die genaue Restkostenabrechnung sind noch zu prüfen.</p>
    {:else if selected==='liquidity'}<div class="hh-detail-row"><span>Erfasste liquide Mittel</span><strong>{money(h.liquid)}</strong></div>{#if h.after_purchase!==null}<div class="hh-detail-row"><span>Kaufpreisbindung</span><strong>− {money(h.property!.price)}</strong></div><div class="hh-detail-row"><span>Rechnerisch nach Kaufpreis</span><strong>{money(h.after_purchase)}</strong></div>{/if}<p>Stände verschiedener Auszugstage; noch vor restlichen Erwerbskosten. Kein heutiger verfügbarer Kontostand. Wertpapiere sind hier nicht als Bargeld gerechnet.</p>
    {:else if selected==='projection'&&h.forecast}<div class="hh-detail-row"><span>Bereinigter Monatsmedian</span><strong>{money(h.forecast.baseline)}</strong></div><div class="hh-detail-row"><span>Beobachtete Basis</span><strong>{h.forecast.basis_months.map(m=>monthLabel(m,true)).join(' · ')}</strong></div><div class="hh-detail-row"><span>Planungsband</span><strong>± {money(h.forecast.band)}</strong></div><p>Die Haushaltsansicht entfernt bestätigte Eigenüberträge. Belegte und gekennzeichnete geschätzte Umtauschgebühren bleiben als Aufwand enthalten. Für den Ausblick werden zusätzlich hinterlegte Familiendurchläufe sowie Technikanschaffungen und ihre Erstattungen vorläufig herausgerechnet. Ungeklärte Überträge bleiben enthalten. Nachschüssige Auszahlung der befristeten Einnahme angenommen; der letzte Leistungsmonat wird kalendertäglich anteilig gerechnet. Das Band ist eine Planungsannahme, keine statistische Sicherheit.</p><p>Hauskauf separat in der Kapitalbindung. Keine neuen Mieteinnahmen und keine fortgeschriebenen Tagesgeldzinsen. Eine Projektion erscheint nur anschließend an den letzten belegten Monat.</p>
    {:else}<div class="hh-detail-row"><span>Diagramme</span><strong>Buchungsmonat · gemeinsame Zeitachse</strong></div><div class="hh-detail-row"><span>Umrechnung</span><strong>{h.fx_source} · {h.fx_date}</strong></div>{#each h.accounts as a}<div class="hh-detail-row"><span>{a.label}</span><strong>{a.as_of}</strong></div>{/each}<p>Die Symbole oben zeigen den jüngsten erfassten Vermögensstand. Der Regler filtert die historischen Diagramme. Kategorien sind Vorschläge aus Buchungstexten. Bestätigte Eigenüberträge sind aus dem Haushalt herausgerechnet und unter Überträge nachvollziehbar. Kontobewegungen zeigt unveränderte Bruttowerte. Gebühren sind entweder belegt oder anhand ähnlicher, zeitnaher Transfers geschätzt; unbekannte Gebühren sind nicht als null bestätigt. Historisch fehlen teilweise Konten: die Anzeige bedeutet keine vollständige Haushaltsbilanz.</p>{#if h.transfer_history}<div class="hh-detail-row"><span>Transferabgleich</span><strong>{h.transfer_history.bank_legs} Bankbewegungen · {h.transfer_history.paired_legs} mit beiden Bankseiten</strong></div><p>Wise: {h.transfer_history.status==='ready'?`${h.transfer_history.records} Transfers aus ${h.transfer_history.source_count} Quellen`:h.transfer_history.status==='invalid'?'Quellprüfung fehlgeschlagen':'Transaktionshistorie fehlt'}. {#if h.transfer_history.status==='ready'&&h.transfer_history.matched_records!==undefined}{h.transfer_history.matched_records} Transfers im Kontoauszug zugeordnet, {h.transfer_history.records-h.transfer_history.matched_records} ohne passenden Bankbeleg. {/if}IB: Historische Ein-/Auszahlungen und Devisengeschäfte noch offen. Erkennen des Transferdiensts bestätigt noch keine vollständige Transferkette.</p>{/if}<p>Originale werden nur über ihre gebundene Buchung und einen gültigen Sicherheitsnachweis geöffnet. Eine fehlende Rechnung oder Gegenbuchung bedeutet nicht „unbezahlt“.</p><a href="/ledger/books" class="hh-entry-link">Import und Abgleich verwalten →</a>{/if}
   </section>{/if}
   {#if view==='household'&&estimatedFees>0}<p class="hh-small-note">In Ausgaben enthalten: {estimatedFees<100?'unter 100 '+h.currency:money(estimatedFees)} geschätzte Umtauschgebühren. <button class="hh-entry-link" onclick={()=>expenses('transfer_fees')}>Gebührenbasis ↗</button></p>{/if}
   <footer class="hh-footer"><span>{h.currency} · Übersicht auf 100 gerundet · Kategorien vorläufig</span><button onclick={()=>expenses()}>Einzelne Buchungen & Belege <ArrowRight size={12}/></button></footer>
   </div>
   <section id="household-categories" class="hh-panel hh-expenses-panel" bind:this={treePanel}>
    <div class="hh-panel-top"><div><h2>{treeDirection==='debit'?(view==='household'?'Ausgaben':'Abgänge'):(view==='household'?'Einnahmen':'Zugänge')}</h2><p>{treeMonth?monthLabel(treeMonth,true):period}{view==='household'?'':' · brutto'}</p></div><strong class="hh-total">{money(treeTotal)}</strong></div>
    <div class="hh-tree-controls"><div class="hh-proj" aria-label="Kategorienansicht"><button aria-pressed={treeDirection==='debit'} onclick={()=>treeDirection='debit'}>{view==='household'?'Ausgaben':'Abgänge'}</button><button class:hh-expiring={view!=='transfers'&&sources.some(s=>s.days!==null&&s.days<=30)} aria-pressed={treeDirection==='credit'} onclick={()=>treeDirection='credit'}>{view==='household'?'Einnahmen':'Zugänge'}{#if view!=='transfers'&&sources.some(s=>s.days!==null&&s.days<=30)}<i aria-label="Laufzeit beachten"></i>{/if}</button></div>{#if treeMonth}<button class="hh-reset" onclick={()=>treeMonth=''}>Gesamter Zeitraum <X size={12}/></button>{/if}</div>
    {#key `${treeMonths[0].month}:${treeMonths.at(-1)!.month}:${h.batch_sha256}:${treeDirection}`}<HouseholdExpenses {view} months={treeMonths} {money} batch={h.batch_sha256} direction={treeDirection} initialCategory={treeCategory}/>{/key}
    <p class="hh-small-note">Kategorie → Untergruppe → {treeDirection==='debit'?'Anbieter':'Absender'} → Buchung → Beleg</p>
   </section>
   </div>
  {/if}
 </div>
</main>

<style>.hh-view-switch{display:flex;gap:4px;flex-wrap:wrap;width:fit-content;margin:0 0 24px}.hh-view-switch button{padding:8px 12px;font-size:12px}</style>
